CREATE TABLE IF NOT EXISTS voters (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255) UNIQUE NOT NULL,
  full_name     VARCHAR(255)        NOT NULL,
  pesel_hash    VARCHAR(64)         NOT NULL,
  blocked       BOOLEAN             NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMP           NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_voters_pesel_hash UNIQUE (pesel_hash)
);

CREATE TABLE IF NOT EXISTS elections (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(255) NOT NULL,
  description   TEXT,
  starts_at     TIMESTAMP    NOT NULL,
  ends_at       TIMESTAMP    NOT NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_election_time CHECK (starts_at < ends_at)
);

CREATE TABLE IF NOT EXISTS election_options (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_id   BIGINT NOT NULL REFERENCES elections(id) ON DELETE CASCADE,
  label         VARCHAR(255) NOT NULL,
  UNIQUE (election_id, label)
);

CREATE TABLE IF NOT EXISTS votes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_id     BIGINT NOT NULL REFERENCES elections(id) ON DELETE CASCADE,
  voter_id        BIGINT NOT NULL REFERENCES voters(id)    ON DELETE CASCADE,
  option_id       BIGINT NOT NULL REFERENCES election_options(id) ON DELETE CASCADE,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (election_id, voter_id)
);

CREATE INDEX IF NOT EXISTS idx_votes_election ON votes(election_id);
CREATE INDEX IF NOT EXISTS idx_votes_option   ON votes(option_id);